# Generated by Django 3.2 on 2024-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROYECTO', '0005_metapersonal_usuario_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('entrenamiento', models.PositiveIntegerField(help_text='Horas de entrenamiento')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en días')),
                ('rutina', models.CharField(help_text='Nombre de la rutina', max_length=255)),
                ('link_descarga', models.URLField(help_text='Link de descarga de Excel')),
                ('entrenador', models.CharField(blank=True, help_text='Entrenador responsable', max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='metapersonal',
            name='usuario_responsable',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
